# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 665ded82ceb911b05a2543ddc3036a65f44671e3590fd0d172a7bb2490f1b7da2bd01c4fe20190f7d3a6984bc56d2b282a7a3b2b634921d13730c379b714c75c

test:
  secret_key_base: c44ee1fff33d48604662c215301e6ebac85f7d20fd7c72353b8fd9723e173a173dfade4b7c60830c37f6d664a5ff91194c91c2d69133b54e9643d3474e8f385f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
